import { GeneratedRoute } from '../types/route';

/**
 * Production-Grade GPX 1.1 File Exporter
 * Generates standards-compliant XML for Garmin, Strava, Wahoo, Apple Watch, and COROS.
 */
export function generateGpxString(route: GeneratedRoute): string {
  const timeCreated = route.createdAt || new Date().toISOString();
  const sanitizedName = (route.name || 'Exported_Route').replace(/[<>&'"]/g, '');
  const description = `Generated by GPS Art & Spatial Route Generator. Activity: ${route.activity}, Distance: ${route.stats.distanceKm} km, Elevation Gain: ${route.stats.elevationGainM} m.`;

  // Base timestamp for trkpt calculation (simulating moving track at steady workout pace)
  const startTime = new Date(timeCreated).getTime();
  const totalSeconds = (route.stats.estimatedDurationMinutes || 30) * 60;
  const timeStepSeconds = route.coordinates.length > 1 ? totalSeconds / (route.coordinates.length - 1) : 1;

  let trkptsXml = '';
  for (let i = 0; i < route.coordinates.length; i++) {
    const [lat, lng] = route.coordinates[i];
    const elePoint = route.elevationProfile[i] || route.elevationProfile[route.elevationProfile.length - 1];
    const elevation = elePoint ? elePoint.elevation : 30;
    const ptTime = new Date(startTime + i * timeStepSeconds * 1000).toISOString();

    trkptsXml += `      <trkpt lat="${lat.toFixed(6)}" lon="${lng.toFixed(6)}">\n`;
    trkptsXml += `        <ele>${elevation.toFixed(1)}</ele>\n`;
    trkptsXml += `        <time>${ptTime}</time>\n`;
    trkptsXml += `      </trkpt>\n`;
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GPS Art &amp; Route Generator - https://routecraft.spatial"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>${sanitizedName}</name>
    <desc>${description}</desc>
    <author>
      <name>GPS Art Spatial Engine</name>
    </author>
    <time>${timeCreated}</time>
  </metadata>
  <trk>
    <name>${sanitizedName}</name>
    <desc>${description}</desc>
    <type>${route.activity.toUpperCase()}</type>
    <trkseg>
${trkptsXml}    </trkseg>
  </trk>
</gpx>`;
}

/**
 * Triggers a client-side file download of the GPX file
 */
export function downloadGpxFile(route: GeneratedRoute): void {
  const gpxContent = generateGpxString(route);
  const blob = new Blob([gpxContent], { type: 'application/gpx+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  const fileNameSafe = (route.name || 'route')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  link.download = `${fileNameSafe}_${Date.now()}.gpx`;
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
